### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by nygdjs** [bkbooth/color-gutter#12]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.3
**Thrown From**: [color-gutter](https://github.com/bkbooth/color-gutter) package, v0.4.1
### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1022

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1022:15)
  at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/marker.js:176:33)
  at new Marker (/Applications/Atom.app/Contents/Resources/app/src/marker.js:36:41)
  at DisplayBuffer.module.exports.DisplayBuffer.getMarker (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1247:20)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1287:19)
  at TextEditor.module.exports.TextEditor.markBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1232:62)
  at ColorGutterView.module.exports.ColorGutterView.markLine (/Users/norbert/.atom/packages/color-gutter/lib/color-gutter-view.coffee:76:22)
  at ColorGutterView.<anonymous> (/Users/norbert/.atom/packages/color-gutter/lib/color-gutter-view.coffee:67:14)
  at ColorGutterView.module.exports.ColorGutterView.updateColors (/Users/norbert/.atom/packages/color-gutter/lib/color-gutter-view.coffee:89:14)
  at /Users/norbert/.atom/packages/color-gutter/lib/color-gutter-view.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:550:20)
  at BufferPatch.module.exports.BufferPatch.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/buffer-patch.js:57:21)
  at Transaction.module.exports.Transaction.applyTo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/transaction.js:70:15)
  at History.module.exports.History.abortTransaction (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:169:24)
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:126:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:647:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1107:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```
### Commands

```
  6x -1:46.6 core:backspace (atom-text-editor.editor)
  2x -1:42.9 core:select-to-top (atom-text-editor.editor)
  2x -1:41.5 core:select-to-bottom (atom-text-editor.editor)
     -1:37.3 editor:select-to-first-character-of-line (atom-text-editor.editor)
     -1:36.4 core:backspace (atom-text-editor.editor)
     -1:34.5 core:undo (atom-text-editor.editor)
     -1:24.5 settings-view:open (atom-text-editor.editor.is-focused)
     -0:26.4 core:move-right (atom-text-editor.editor.is-focused)
     -0:25.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:23.7 editor:consolidate-selections (atom-text-editor.editor.is-focused)
  3x -0:18.7 find-and-replace:find-next (atom-text-editor.editor.is-focused)
     -0:16.5 find-and-replace:select-next (atom-text-editor.editor.is-focused)
  2x -0:14.5 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:14.1 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.1 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:01.1 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "audioBeep": false,
    "projectHome": "Users/norbert/quince/"
  },
  "color-gutter": {}
}
```
### Installed Packages

``` coffee
# User
color-gutter, v0.4.1
color-picker, v1.6.0
emmet, v2.3.7
grunt-runner, v0.8.0
language-SCSS, v0.2.0
linter-scss-lint, v0.0.14
preview-plus, v1.1.19
project-colorize, v0.1.0
save-session, v0.13.5
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by bkbooth** [comment]
I've had this package unpublished for over 2 years now. I'm not maintaining it anymore so closing this issue.
